CREATE TABLE ORCAMENTO (
                ID_ORCAMENTO BIGINT IDENTITY NOT NULL,
                DATA_ORCAMENTO DATE NOT NULL,
                DATA_VENCIMENTO DATE NOT NULL,
                VALOR NUMERIC(9,2) NOT NULL,
                CONSTRAINT ORCAMENTO_pk PRIMARY KEY (ID_ORCAMENTO)
)