CREATE TABLE PEDIDO (
                ID_PEDIDO BIGINT IDENTITY NOT NULL,
                DATA_EMISSAO DATE NOT NULL,
                CLIENTE VARCHAR(100) NOT NULL,
                ID_ORCAMENTO BIGINT NOT NULL,
                CONSTRAINT PEDIDO_pk PRIMARY KEY (ID_PEDIDO),
				CONSTRAINT ORCAMENTO_PEDIDO_fk FOREIGN KEY (ID_ORCAMENTO) REFERENCES ORCAMENTO(ID_ORCAMENTO)
)